name: PR CI
on:
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Add ssh private key to the server
        run: |
          mkdir -p $HOME/.ssh/
          chmod 700 $HOME/.ssh/
          echo -n "${{ secrets.SSH_KEY_PRIVATE }}" | base64 --decode > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          stat $HOME/.ssh/id_rsa
          
      - name: Check Access
        run: ssh -T git@github.com

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test:unit
