name: PR CI
on:
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - actions/checkout@v1
      # Make sure the @v0.2.0 matches the current version of the
      # action 
      - uses: webfactory/ssh-agent@v0.2.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Check Access
        run: ssh -T git@github.com

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test:unit
