name: PR CI
on:
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Dependencies
        run: yarn install
